channels:
- conda-forge
dependencies:
- python=3.9.12
- pip<=21.2.4
- pip:
  - mlflow
  - cloudpickle==2.0.0
  - ipywidgets==7.6.5
  - mypy-extensions==0.4.3
  - python-snappy==0.6.0
  - scikit-learn==1.0.2
  - seaborn==0.11.2
  - statsmodels==0.13.2
  - xgboost==1.6.2
name: mlflow-env
