name: model-training
on: [push]
jobs:
  run:
    permissions: write-all
    runs-on: ubuntu-latest
    # optionally use a convenient Ubuntu LTS + DVC + CML image
    # container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v2
      # may need to setup NodeJS & Python3 on e.g. self-hosted
      # - uses: actions/setup-node@v2
      #   with:
      #     node-version: '16'
      # - uses: actions/setup-python@v2
      #   with:
      #     python-version: '3.x'
      - uses: iterative/setup-cml@v1
      - name: Train model
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          python training/train.py
      - name: Write CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Post reports as comments in GitHub PRs
          echo "### Logistic Regression Model Metrics" > report.md
          cat training/logistic_regression_metrics.txt >> report.md
          echo "### Data Visualization" >> report.md
          cml-publish training/logistic_regression_accuracy.png --md >> report.md
          echo "### Random Forest Classifier Model Metrics" > report.md
          cat training/random_forest_classifier_metrics.txt >> report.md
          echo "### Data Visualization" >> report.md
          cml-publish training/random_forest_classifier_accuracy.png --md >> report.md
          echo "### XGBClassifier Model Metrics" > report.md
          cat training/xgb_classifier_metrics.txt >> report.md
          echo "### Data Visualization" >> report.md
          cml-publish training/xgb_classifier_accuracy.png --md >> report.md
          echo "### Decision Tree Classifier Model Metrics" > report.md
          cat training/decision_tree_classifier_metrics.txt >> report.md
          echo "### Data Visualization" >> report.md
          cml-publish training/decision_tree_classifier_accuracy.png --md >> report.md
          cml-send-comment report.md